In [2]:
import numpy as np
import pandas as pd

In [3]:
import os

directory = os.getcwd()
data = pd.read_csv(directory + '/EMS_2017_2018.csv', sep=',') 
data = pd.DataFrame(data)

## Heat map: Police precent Lat Long - 


## add in the code names to original dataset for reference

In [38]:
data_wrk = data[['Incident_Date', 'Incident_Time', 'INITIAL_CALL_TYPE', 'INITIAL_SEVERITY_LEVEL_CODE', 'FINAL_CALL_TYPE', 'FINAL_SEVERITY_LEVEL_CODE', 'INCIDENT_TRAVEL_TM_SECONDS_QY', 'HELD_INDICATOR', 'INCIDENT_DISPOSITION_CODE', 'BOROUGH', 'ZIPCODE', 'POLICEPRECINCT', 'INCIDENT_DISPATCH_AREA']]

In [39]:
data_wrk

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6
1,11:59:20 PM,12/31/2018,MVAINJ,4,MVAINJ,4,369.0,N,91.0,QUEENS,11416.0,102.0,Q3
2,11:58:45 PM,12/31/2018,SICK,6,SICK,6,815.0,N,82.0,QUEENS,11369.0,115.0,Q6
3,11:58:14 PM,12/31/2018,INJMAJ,3,INJMAJ,3,348.0,N,82.0,BROOKLYN,11214.0,62.0,K1
4,11:57:42 PM,12/31/2018,UNC,2,UNC,2,861.0,N,82.0,MANHATTAN,10019.0,18.0,M3
5,11:57:41 PM,12/31/2018,SICMIN,7,SICMIN,7,1651.0,N,93.0,BROOKLYN,11208.0,75.0,K4
6,11:57:06 PM,12/31/2018,UNKNOW,4,UNKNOW,4,308.0,N,82.0,QUEENS,11435.0,107.0,Q5
7,11:57:04 PM,12/31/2018,CARDBR,2,CARDBR,2,21.0,N,82.0,BRONX,10465.0,45.0,B3
8,11:55:49 PM,12/31/2018,INJURY,5,INJURY,5,327.0,N,82.0,QUEENS,11691.0,101.0,Q1
9,11:55:27 PM,12/31/2018,INJURY,5,INJURY,5,524.0,Y,82.0,BRONX,10453.0,46.0,B2
10,11:55:23 PM,12/31/2018,ASTHMB,2,ASTHMB,2,326.0,N,82.0,BROOKLYN,11233.0,77.0,K5
11,11:54:02 PM,12/31/2018,DRUG,4,DRUG,4,411.0,Y,82.0,BROOKLYN,11233.0,73.0,K4
12,11:53:51 PM,12/31/2018,DRUG,4,DRUG,4,166.0,N,82.0,MANHATTAN,10004.0,1.0,M1
13,11:53:30 PM,12/31/2018,DRUG,4,DRUG,4,668.0,Y,82.0,MANHATTAN,10019.0,18.0,M3
14,11:53:23 PM,12/31/2018,UNKNOW,4,UNKNOW,4,401.0,N,90.0,BROOKLYN,11237.0,83.0,K7
15,11:52:40 PM,12/31/2018,STATEP,2,STATEP,2,790.0,N,82.0,RICHMOND / STATEN ISLAND,10301.0,120.0,S1
16,11:52:09 PM,12/31/2018,DIFFBR,2,DIFFBR,2,295.0,N,82.0,QUEENS,11427.0,105.0,Q2
17,11:52:03 PM,12/31/2018,SICPED,4,SICPED,4,324.0,N,82.0,RICHMOND / STATEN ISLAND,10301.0,120.0,S1
18,11:51:39 PM,12/31/2018,SEIZR,3,SEIZR,3,526.0,N,82.0,BRONX,10454.0,40.0,B1
19,11:51:28 PM,12/31/2018,UNC,2,UNC,2,459.0,N,93.0,QUEENS,11433.0,103.0,Q2
20,11:51:00 PM,12/31/2018,MVAINJ,4,MVAINJ,4,816.0,Y,93.0,BRONX,10459.0,41.0,B1
21,11:50:49 PM,12/31/2018,SICK,6,SICK,6,343.0,N,93.0,BROOKLYN,11224.0,60.0,K1
22,11:50:47 PM,12/31/2018,INJMAJ,3,INJMAJ,3,373.0,N,82.0,BROOKLYN,11225.0,71.0,K3
23,11:50:38 PM,12/31/2018,EDP,7,EDPC,5,636.0,Y,82.0,BRONX,10467.0,49.0,B4
24,11:50:12 PM,12/31/2018,PEDSTR,3,PEDSTR,3,215.0,N,96.0,BRONX,10456.0,44.0,B2
25,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6
26,11:49:41 PM,12/31/2018,UNKNOW,4,UNKNOW,4,436.0,N,93.0,BROOKLYN,11218.0,66.0,K2
27,11:49:28 PM,12/31/2018,SEIZR,3,SEIZR,3,637.0,N,93.0,MANHATTAN,10037.0,32.0,M8
28,11:49:19 PM,12/31/2018,DRUG,4,DRUG,4,289.0,Y,82.0,MANHATTAN,10036.0,14.0,M3
29,11:48:57 PM,12/31/2018,INJMAJ,3,DRUG,4,405.0,N,96.0,BROOKLYN,11216.0,79.0,K5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001458,12:07:07 AM,01/01/2017,UNKNOW,4,UNKNOW,4,837.0,N,82.0,BROOKLYN,11229.0,61.0,K1
3001459,12:06:49 AM,01/01/2017,RESPIR,4,RESPIR,4,308.0,N,82.0,QUEENS,11364.0,111.0,Q7
3001460,12:06:40 AM,01/01/2017,INJMAJ,3,INJMAJ,3,437.0,N,93.0,BROOKLYN,11209.0,68.0,K2
3001461,12:06:26 AM,01/01/2017,INJURY,5,INJURY,5,336.0,N,93.0,BRONX,10453.0,46.0,B2
3001462,12:06:20 AM,01/01/2017,DRUG,4,DRUG,4,1213.0,N,87.0,MANHATTAN,10011.0,10.0,M2
3001463,12:06:16 AM,01/01/2017,UNKNOW,4,UNKNOW,4,374.0,N,90.0,QUEENS,11420.0,106.0,Q3
3001464,12:06:05 AM,01/01/2017,EDP,7,EDP,7,793.0,N,82.0,QUEENS,11420.0,106.0,Q3
3001465,12:05:58 AM,01/01/2017,DIFFBR,2,DIFFBR,2,639.0,N,93.0,MANHATTAN,10009.0,9.0,M2
3001466,12:05:29 AM,01/01/2017,SHOT,3,SHOT,3,453.0,N,82.0,BROOKLYN,11212.0,73.0,K4
3001467,12:05:28 AM,01/01/2017,ALTMEN,3,ALTMEN,3,313.0,N,82.0,QUEENS,11370.0,114.0,Q6
3001468,12:05:22 AM,01/01/2017,DRUG,4,DRUG,4,526.0,N,82.0,MANHATTAN,10002.0,7.0,M1
3001469,12:05:18 AM,01/01/2017,INJURY,5,INJURY,5,670.0,N,82.0,MANHATTAN,10032.0,33.0,M9
3001470,12:04:50 AM,01/01/2017,DRUG,4,DRUG,4,204.0,N,96.0,MANHATTAN,10001.0,13.0,X1
3001471,12:04:31 AM,01/01/2017,DRUG,4,DRUG,4,396.0,N,93.0,BRONX,10462.0,43.0,B3
3001472,12:04:06 AM,01/01/2017,DIFFBR,2,DIFFBR,2,415.0,N,82.0,QUEENS,11421.0,102.0,Q3
3001473,12:04:05 AM,01/01/2017,DRUG,4,DRUG,4,281.0,N,90.0,MANHATTAN,10020.0,18.0,M3
3001474,12:03:35 AM,01/01/2017,UNC,2,UNC,2,399.0,N,96.0,MANHATTAN,10019.0,18.0,M3
3001475,12:03:33 AM,01/01/2017,DRUG,4,DRUG,4,429.0,N,96.0,MANHATTAN,10036.0,10.0,M2
3001476,12:03:19 AM,01/01/2017,SEIZR,3,SEIZR,3,326.0,N,93.0,BROOKLYN,11206.0,79.0,K7
3001477,12:03:11 AM,01/01/2017,ARREST,1,ARREST,1,229.0,N,82.0,RICHMOND / STATEN ISLAND,10312.0,123.0,S3
3001478,12:03:07 AM,01/01/2017,INJURY,5,INJURY,5,595.0,N,82.0,QUEENS,11420.0,106.0,Q3
3001479,12:02:52 AM,01/01/2017,UNKNOW,4,UNKNOW,4,464.0,N,82.0,BROOKLYN,11226.0,70.0,K2
3001480,12:02:42 AM,01/01/2017,DRUG,4,DRUG,4,0.0,N,82.0,MANHATTAN,10001.0,10.0,M2
3001481,12:02:07 AM,01/01/2017,DRUG,4,DRUG,4,1163.0,N,96.0,MANHATTAN,10014.0,6.0,M2
3001482,12:02:05 AM,01/01/2017,EDP,7,EDP,7,532.0,N,82.0,BRONX,10456.0,42.0,B1
3001483,12:02:01 AM,01/01/2017,UNC,2,UNC,2,428.0,N,93.0,QUEENS,11436.0,113.0,Q2
3001484,12:01:27 AM,01/01/2017,DRUG,4,DRUG,4,132.0,N,90.0,MANHATTAN,10002.0,7.0,M1
3001485,12:01:13 AM,01/01/2017,OTHER,6,OTHER,6,573.0,N,90.0,MANHATTAN,10001.0,13.0,M2
3001486,12:01:09 AM,01/01/2017,STNDBY,8,STNDBY,8,1956.0,N,87.0,BROOKLYN,NaN,NaN,K1
3001487,12:01:03 AM,01/01/2017,CARD,3,CARD,3,263.0,N,90.0,BROOKLYN,11221.0,83.0,K7

# Cancelled call = NaN removed from original

In [43]:
a = data['INCIDENT_DISPOSITION_CODE'] != 'CANCEL'

/anaconda3/lib/python3.6/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [33]:
a = data['INCIDENT_DISPOSITION_CODE'] != 'DUP'

/anaconda3/lib/python3.6/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [ ]:
a = data['INCIDENT_DISPOSITION_CODE'] != 87

In [46]:
a.describe()

count     3001488
unique          2
top          True
freq      2932322
Name: INCIDENT_DISPOSITION_CODE, dtype: object

In [47]:
3001487 - 2932322  #that were type 87

69165

In [50]:
#87 H A S  B E E N  D R O P P E D 
data_wrk = data_wrk[data_wrk['INCIDENT_DISPOSITION_CODE'] != 87]

In [52]:
data_wrk.describe()

,INITIAL_SEVERITY_LEVEL_CODE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,INCIDENT_DISPOSITION_CODE,ZIPCODE,POLICEPRECINCT
count,2.932322e+06,2.932322e+06,2.872968e+06,2.912435e+06,2.896174e+06,2.896267e+06
mean,4.260933e+00,4.165691e+00,4.896883e+02,8.483722e+01,1.073071e+04,6.135616e+01
std,1.720372e+00,1.720786e+00,3.898286e+02,4.706479e+00,5.497261e+02,3.418117e+01
min,1.000000e+00,1.000000e+00,0.000000e+00,8.200000e+01,8.300000e+01,1.000000e+00
25%,3.000000e+00,3.000000e+00,2.830000e+02,8.200000e+01,1.012800e+04,3.400000e+01
50%,4.000000e+00,4.000000e+00,4.050000e+02,8.200000e+01,1.046900e+04,6.000000e+01
75%,6.000000e+00,6.000000e+00,5.830000e+02,9.000000e+01,1.122600e+04,8.800000e+01
max,9.000000e+00,8.000000e+00,8.738600e+04,9.600000e+01,1.234500e+04,1.230000e+02

In [55]:
data_wrk['Incident_Date']  #convert to panadas timseries

0          11:59:46 PM
1          11:59:20 PM
2          11:58:45 PM
3          11:58:14 PM
4          11:57:42 PM
              ...
3001482    12:02:05 AM
3001483    12:02:01 AM
3001484    12:01:27 AM
3001485    12:01:13 AM
3001487    12:01:03 AM
Name: Incident_Date, Length: 2932322, dtype: object

In [56]:
data_wrk['Incident_Time']  #convert to panadas timseries

0          12/31/2018
1          12/31/2018
2          12/31/2018
3          12/31/2018
4          12/31/2018
              ...
3001482    01/01/2017
3001483    01/01/2017
3001484    01/01/2017
3001485    01/01/2017
3001487    01/01/2017
Name: Incident_Time, Length: 2932322, dtype: object

In [70]:
data_wrk.isna().sum()

Incident_Date                        0
Incident_Time                        0
INITIAL_CALL_TYPE                    0
INITIAL_SEVERITY_LEVEL_CODE          0
FINAL_CALL_TYPE                      0
FINAL_SEVERITY_LEVEL_CODE            0
INCIDENT_TRAVEL_TM_SECONDS_QY    59354
HELD_INDICATOR                       0
INCIDENT_DISPOSITION_CODE        19887
BOROUGH                              0
ZIPCODE                          36148
POLICEPRECINCT                   36055
INCIDENT_DISPATCH_AREA               0
dtype: int64

In [96]:
data_wrk[data_wrk.isna().any(axis=1)]

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA
56,11:42:18 PM,12/31/2018,INJMIN,7,INJMIN,7,NaN,N,96.0,BROOKLYN,11230.0,66.0,K2
94,11:31:55 PM,12/31/2018,UNKNOW,4,UNKNOW,4,NaN,N,NaN,RICHMOND / STATEN ISLAND,10310.0,120.0,S1
110,11:26:33 PM,12/31/2018,MVAINJ,4,MVAINJ,4,416.0,N,91.0,QUEENS,NaN,NaN,Q7
150,11:14:00 PM,12/31/2018,SICK,6,SICK,6,149.0,N,93.0,BRONX,NaN,NaN,B3
194,11:00:43 PM,12/31/2018,OTHER,6,OTHER,6,NaN,Y,NaN,BROOKLYN,11207.0,75.0,K4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001221,12:56:11 AM,01/01/2017,STNDBY,8,STNDBY,8,NaN,Y,NaN,MANHATTAN,10040.0,34.0,M9
3001234,12:54:45 AM,01/01/2017,DRUG,4,DRUG,4,430.0,N,90.0,MANHATTAN,NaN,NaN,X1
3001411,12:19:31 AM,01/01/2017,SHOT,3,SHOT,3,NaN,N,90.0,BROOKLYN,11210.0,70.0,K3
3001415,12:18:36 AM,01/01/2017,MVAINJ,4,MVAINJ,4,456.0,N,90.0,QUEENS,NaN,NaN,Q7
3001440,12:11:34 AM,01/01/2017,MVAINJ,4,MVAINJ,4,345.0,N,91.0,QUEENS,NaN,NaN,Q3

In [97]:
data.iloc[94]

Unnamed: 0                                              94
CAD_INCIDENT_ID                                  183654276
INCIDENT_DATETIME                   12/31/2018 11:31:55 PM
INITIAL_CALL_TYPE                                   UNKNOW
INITIAL_SEVERITY_LEVEL_CODE                              4
FINAL_CALL_TYPE                                     UNKNOW
FINAL_SEVERITY_LEVEL_CODE                                4
FIRST_ASSIGNMENT_DATETIME                              NaN
VALID_DISPATCH_RSPNS_TIME_INDC                           N
DISPATCH_RESPONSE_SECONDS_QY                             0
FIRST_ACTIVATION_DATETIME                              NaN
FIRST_ON_SCENE_DATETIME                                NaN
VALID_INCIDENT_RSPNS_TIME_INDC                           N
INCIDENT_RESPONSE_SECONDS_QY                           NaN
INCIDENT_TRAVEL_TM_SECONDS_QY                          NaN
FIRST_TO_HOSP_DATETIME                                 NaN
FIRST_HOSP_ARRIVAL_DATETIME                            NaN
INCIDENT_CLOSE_DATETIME             12/31/2018 11:34:03 PM
HELD_INDICATOR                                           N
INCIDENT_DISPOSITION_CODE                              NaN
BOROUGH                           RICHMOND / STATEN ISLAND
INCIDENT_DISPATCH_AREA                                  S1
ZIPCODE                                              10310
POLICEPRECINCT                                         120
CITYCOUNCILDISTRICT                                     49
COMMUNITYDISTRICT                                      501
COMMUNITYSCHOOLDISTRICT                                 31
CONGRESSIONALDISTRICT                                   11
REOPEN_INDICATOR                                         N
SPECIAL_EVENT_INDICATOR                                  N
STANDBY_INDICATOR                                        N
TRANSFER_INDICATOR                                       N
Incident_Time                                   12/31/2018
Incident_Date                                  11:31:55 PM
Name: 94, dtype: object

In [98]:
data.iloc[56]

Unnamed: 0                                            56
CAD_INCIDENT_ID                                183654316
INCIDENT_DATETIME                 12/31/2018 11:42:18 PM
INITIAL_CALL_TYPE                                 INJMIN
INITIAL_SEVERITY_LEVEL_CODE                            7
FINAL_CALL_TYPE                                   INJMIN
FINAL_SEVERITY_LEVEL_CODE                              7
FIRST_ASSIGNMENT_DATETIME         12/31/2018 11:42:41 PM
VALID_DISPATCH_RSPNS_TIME_INDC                         Y
DISPATCH_RESPONSE_SECONDS_QY                          23
FIRST_ACTIVATION_DATETIME         12/31/2018 11:42:50 PM
FIRST_ON_SCENE_DATETIME                              NaN
VALID_INCIDENT_RSPNS_TIME_INDC                         N
INCIDENT_RESPONSE_SECONDS_QY                         NaN
INCIDENT_TRAVEL_TM_SECONDS_QY                        NaN
FIRST_TO_HOSP_DATETIME                               NaN
FIRST_HOSP_ARRIVAL_DATETIME                          NaN
INCIDENT_CLOSE_DATETIME           12/31/2018 11:57:15 PM
HELD_INDICATOR                                         N
INCIDENT_DISPOSITION_CODE                             96
BOROUGH                                         BROOKLYN
INCIDENT_DISPATCH_AREA                                K2
ZIPCODE                                            11230
POLICEPRECINCT                                        66
CITYCOUNCILDISTRICT                                   44
COMMUNITYDISTRICT                                    312
COMMUNITYSCHOOLDISTRICT                               21
CONGRESSIONALDISTRICT                                  9
REOPEN_INDICATOR                                       N
SPECIAL_EVENT_INDICATOR                                N
STANDBY_INDICATOR                                      N
TRANSFER_INDICATOR                                     N
Incident_Time                                 12/31/2018
Incident_Date                                11:42:18 PM
Name: 56, dtype: object

In [100]:
a = data[data['INCIDENT_DISPOSITION_CODE'] == 96]

In [103]:
a.isna().sum()

Unnamed: 0                             0
CAD_INCIDENT_ID                        0
INCIDENT_DATETIME                      0
INITIAL_CALL_TYPE                      0
INITIAL_SEVERITY_LEVEL_CODE            0
FINAL_CALL_TYPE                        0
FINAL_SEVERITY_LEVEL_CODE              0
FIRST_ASSIGNMENT_DATETIME              0
VALID_DISPATCH_RSPNS_TIME_INDC         0
DISPATCH_RESPONSE_SECONDS_QY           0
FIRST_ACTIVATION_DATETIME            120
FIRST_ON_SCENE_DATETIME             2683
VALID_INCIDENT_RSPNS_TIME_INDC         0
INCIDENT_RESPONSE_SECONDS_QY        2691
INCIDENT_TRAVEL_TM_SECONDS_QY       2687
FIRST_TO_HOSP_DATETIME            110661
FIRST_HOSP_ARRIVAL_DATETIME       110683
INCIDENT_CLOSE_DATETIME                0
HELD_INDICATOR                         0
INCIDENT_DISPOSITION_CODE              0
BOROUGH                                0
INCIDENT_DISPATCH_AREA                 0
ZIPCODE                             1286
POLICEPRECINCT                      1283
CITYCOUNCILDISTRICT                 1285
COMMUNITYDISTRICT                   1283
COMMUNITYSCHOOLDISTRICT             1362
CONGRESSIONALDISTRICT               1285
REOPEN_INDICATOR                       0
SPECIAL_EVENT_INDICATOR                0
STANDBY_INDICATOR                      0
TRANSFER_INDICATOR                     0
Incident_Time                          0
Incident_Date                          0
dtype: int64

# Remove where disposition == 96 && INCIDENT_TRAVEL_TM_SECONDS_QY!= NaN

In [105]:
a.shape

(110753, 34)

In [107]:
data_wrk['INCIDENT_DISPATCH_AREA'].unique()

array(['K6', 'Q3', 'Q6', 'K1', 'M3', 'K4', 'Q5', 'B3', 'Q1', 'B2', 'K5',
       'M1', 'K7', 'S1', 'Q2', 'B1', 'K3', 'B4', 'K2', 'M8', 'M4', 'M2',
       'M5', 'M7', 'Q7', 'M9', 'B5', 'S3', 'Q4', 'M6', 'S2', 'X1', 'CW',
       'X2', 'X3', 'X5', 'X4', 'C1', 'BO'], dtype=object)

# From whoel data mode of ^^^^^

In [108]:
data.iloc[296]

Unnamed: 0                                           299
CAD_INCIDENT_ID                                183654050
INCIDENT_DATETIME                 12/31/2018 10:33:43 PM
INITIAL_CALL_TYPE                                  OTHER
INITIAL_SEVERITY_LEVEL_CODE                            6
FINAL_CALL_TYPE                                    OTHER
FINAL_SEVERITY_LEVEL_CODE                              6
FIRST_ASSIGNMENT_DATETIME                            NaN
VALID_DISPATCH_RSPNS_TIME_INDC                         N
DISPATCH_RESPONSE_SECONDS_QY                           0
FIRST_ACTIVATION_DATETIME                            NaN
FIRST_ON_SCENE_DATETIME                              NaN
VALID_INCIDENT_RSPNS_TIME_INDC                         N
INCIDENT_RESPONSE_SECONDS_QY                         NaN
INCIDENT_TRAVEL_TM_SECONDS_QY                        NaN
FIRST_TO_HOSP_DATETIME                               NaN
FIRST_HOSP_ARRIVAL_DATETIME                          NaN
INCIDENT_CLOSE_DATETIME           12/31/2018 10:33:43 PM
HELD_INDICATOR                                         N
INCIDENT_DISPOSITION_CODE                            NaN
BOROUGH                                            BRONX
INCIDENT_DISPATCH_AREA                                B3
ZIPCODE                                            10462
POLICEPRECINCT                                        43
CITYCOUNCILDISTRICT                                   18
COMMUNITYDISTRICT                                    209
COMMUNITYSCHOOLDISTRICT                               11
CONGRESSIONALDISTRICT                                 14
REOPEN_INDICATOR                                       N
SPECIAL_EVENT_INDICATOR                                N
STANDBY_INDICATOR                                      N
TRANSFER_INDICATOR                                     N
Incident_Time                                 12/31/2018
Incident_Date                                10:33:43 PM
Name: 299, dtype: object

In [130]:
a = data_wrk[data_wrk['INCIDENT_DISPOSITION_CODE'] == 90.0]

In [137]:
a.isna().sum()

Incident_Date                       0
Incident_Time                       0
INITIAL_CALL_TYPE                   0
INITIAL_SEVERITY_LEVEL_CODE         0
FINAL_CALL_TYPE                     0
FINAL_SEVERITY_LEVEL_CODE           0
INCIDENT_TRAVEL_TM_SECONDS_QY    5668
HELD_INDICATOR                      0
INCIDENT_DISPOSITION_CODE           0
BOROUGH                             0
ZIPCODE                          6829
POLICEPRECINCT                   6807
INCIDENT_DISPATCH_AREA              0
dtype: int64

In [133]:
data_wrk.shape

(2932322, 13)

In [142]:
(271702/2932322 )* 100

9.265762764116628

In [143]:
(5668/2932322) * 100

0.1932939151975806

In [144]:
data_wrk['FINAL_SEVERITY_LEVEL_CODE'].unique()

array([2, 4, 6, 3, 7, 5, 1, 8])

In [145]:
data_wrk['INITIAL_SEVERITY_LEVEL_CODE'].unique()

array([2, 4, 6, 3, 7, 5, 1, 8, 9])

In [146]:
a = data_wrk[data_wrk['INCIDENT_DISPOSITION_CODE'] == 90.0]

In [148]:
a

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA
14,11:53:23 PM,12/31/2018,UNKNOW,4,UNKNOW,4,401.0,N,90.0,BROOKLYN,11237.0,83.0,K7
32,11:48:11 PM,12/31/2018,UNKNOW,4,UNKNOW,4,797.0,N,90.0,MANHATTAN,10017.0,14.0,M3
46,11:44:46 PM,12/31/2018,DRUG,4,DRUG,4,284.0,N,90.0,MANHATTAN,10003.0,9.0,M2
52,11:42:56 PM,12/31/2018,UNKNOW,4,UNKNOW,4,360.0,N,90.0,QUEENS,11411.0,105.0,Q2
55,11:42:28 PM,12/31/2018,INJURY,5,INJMAJ,3,586.0,N,90.0,QUEENS,11364.0,111.0,Q7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001463,12:06:16 AM,01/01/2017,UNKNOW,4,UNKNOW,4,374.0,N,90.0,QUEENS,11420.0,106.0,Q3
3001473,12:04:05 AM,01/01/2017,DRUG,4,DRUG,4,281.0,N,90.0,MANHATTAN,10020.0,18.0,M3
3001484,12:01:27 AM,01/01/2017,DRUG,4,DRUG,4,132.0,N,90.0,MANHATTAN,10002.0,7.0,M1
3001485,12:01:13 AM,01/01/2017,OTHER,6,OTHER,6,573.0,N,90.0,MANHATTAN,10001.0,13.0,M2
3001487,12:01:03 AM,01/01/2017,CARD,3,CARD,3,263.0,N,90.0,BROOKLYN,11221.0,83.0,K7

In [149]:
data.iloc[55]

Unnamed: 0                                            55
CAD_INCIDENT_ID                                183654317
INCIDENT_DATETIME                 12/31/2018 11:42:28 PM
INITIAL_CALL_TYPE                                 INJURY
INITIAL_SEVERITY_LEVEL_CODE                            5
FINAL_CALL_TYPE                                   INJMAJ
FINAL_SEVERITY_LEVEL_CODE                              3
FIRST_ASSIGNMENT_DATETIME         12/31/2018 11:43:17 PM
VALID_DISPATCH_RSPNS_TIME_INDC                         Y
DISPATCH_RESPONSE_SECONDS_QY                          49
FIRST_ACTIVATION_DATETIME         12/31/2018 11:43:30 PM
FIRST_ON_SCENE_DATETIME           12/31/2018 11:53:03 PM
VALID_INCIDENT_RSPNS_TIME_INDC                         Y
INCIDENT_RESPONSE_SECONDS_QY                         635
INCIDENT_TRAVEL_TM_SECONDS_QY                        586
FIRST_TO_HOSP_DATETIME                               NaN
FIRST_HOSP_ARRIVAL_DATETIME                          NaN
INCIDENT_CLOSE_DATETIME           01/01/2019 12:07:12 AM
HELD_INDICATOR                                         N
INCIDENT_DISPOSITION_CODE                             90
BOROUGH                                           QUEENS
INCIDENT_DISPATCH_AREA                                Q7
ZIPCODE                                            11364
POLICEPRECINCT                                       111
CITYCOUNCILDISTRICT                                   23
COMMUNITYDISTRICT                                    411
COMMUNITYSCHOOLDISTRICT                               26
CONGRESSIONALDISTRICT                                  6
REOPEN_INDICATOR                                       N
SPECIAL_EVENT_INDICATOR                                N
STANDBY_INDICATOR                                      N
TRANSFER_INDICATOR                                     N
Incident_Time                                 12/31/2018
Incident_Date                                11:42:28 PM
Name: 55, dtype: object

In [157]:
data_wrk['INITIAL_CALL_TYPE'].unique()

array(['CARDBR', 'MVAINJ', 'SICK', 'INJMAJ', 'UNC', 'SICMIN', 'UNKNOW',
       'INJURY', 'ASTHMB', 'DRUG', 'STATEP', 'DIFFBR', 'SICPED', 'SEIZR',
       'EDP', 'PEDSTR', 'INBLED', 'CARD', 'TRAUMA', 'INJMIN', 'ABDPN',
       'ANAPH', 'GYNMAJ', 'OBLAB', 'CVAC', 'EDPC', 'STAB', 'JUMPUP',
       'PD13', 'ALTMEN', 'OTHER', 'ARREST', 'MEDRXN', 'HYPTN', 'CHOKE',
       'MVA', 'SHOT', 'OBMIS', 'GYNHEM', 'SAFE', 'RESPIR', 'INHALE',
       'CVA', 'BURNMA', 'COLD', 'STNDBY', 'STRANS', 'OBMAJ', 'BURNMI',
       'JUMPDN', 'OBCOMP', 'OBOUT', 'MCI21', 'DROWN', 'EDPW', 'AMPMIN',
       'ACTIVE', 'CHILDA', 'SPEVNT', 'ELECT', 'MCI77', 'VENOM', 'MEDVAC',
       'MVAINM', 'HEAT', 'DIFFFC', 'SICKFC', 'MCI76', 'MOSILL', 'AMPMAJ',
       'PD13C', 'TRAUMS', 'BBP', 'MOSINJ', 'DOA', 'PEDFC', 'MCI22', 'ACC',
       'CARDFC', 'ABDPFC', 'RESPFC', 'ASTHFC', 'NOVEH', 'STATFC',
       'MEDRFC', 'UNCFC', 'ADM', 'PEDRF', 'MCI21P', 'MCI22P', 'CVAFC',
       'SICKRF', 'FIRE77', 'RAPE', 'RADIO', 'MCI80P', 'MCI80', 'INBLFC',
       'CVACFC', 'ALTMFC', 'SEIZFC', 'MCI29P', 'MCI26P', 'DDOA', 'DIFFRF'],
      dtype=object)

In [155]:
len(data_wrk['INITIAL_CALL_TYPE'].unique())

105

In [158]:
data_wrk['FINAL_CALL_TYPE'].unique()

array(['CARDBR', 'MVAINJ', 'SICK', 'INJMAJ', 'UNC', 'SICMIN', 'UNKNOW',
       'INJURY', 'ASTHMB', 'DRUG', 'STATEP', 'DIFFBR', 'SICPED', 'SEIZR',
       'EDPC', 'PEDSTR', 'INBLED', 'CARD', 'EDP', 'TRAUMA', 'INJMIN',
       'ABDPN', 'ANAPH', 'BURNMA', 'GYNMAJ', 'OBLAB', 'CVAC', 'STAB',
       'ALTMEN', 'OTHER', 'ARREST', 'HYPTN', 'CHOKE', 'MVA', 'SHOT',
       'OBMIS', 'MEDRXN', 'GYNHEM', 'SAFE', 'RESPIR', 'CVA', 'INHALE',
       'PD13', 'COLD', 'MCI21', 'OBMAJ', 'STRANS', 'BURNMI', 'JUMPDN',
       'MCI32', 'OBCOMP', 'JUMPUP', 'OBOUT', 'MCI22', 'MCI43', 'STNDBY',
       'EDPW', 'DROWN', 'PD13C', 'ACTIVE', 'AMPMIN', 'CHILDA', 'SPEVNT',
       'ELECT', 'MCI77', 'MEDVAC', 'HEAT', 'VENOM', 'MCI59', 'MCI23',
       'AMPMAJ', 'MCI25', 'DIFFFC', 'MCI34', 'MCI80', 'SICKFC', 'MCI33',
       'CARDFC', 'MCI76', 'DOA', 'MCI24', 'MCI35', 'MCI44', 'MCI38',
       'PEDFC', 'MCI29', 'SICKRF', 'ABDPFC', 'RESPFC', 'ASTHFC', 'SEIZFC',
       'STATFC', 'MCI31', 'MEDRFC', 'UNCFC', 'MCI40', 'DIFFRF', 'PEDRF',
       'MCI32P', 'MCI21P', 'MCI25P', 'MCI22P', 'MCI43P', 'MCI24P',
       'MCI23P', 'MCI35P', 'MCI31P', 'MCI80P', 'MCI34P', 'MCI30P',
       'MCI33P', 'MCI29P', 'MCI59P', 'MCI50P', 'RAPE', 'MCI28P', 'MCI42P',
       'MCI38P', 'MCI44P', 'INBLFC', 'CVAFC', 'CVACFC', 'ALTMFC',
       'SICKFT', 'MCI26P'], dtype=object)

In [156]:
len(data_wrk['FINAL_CALL_TYPE'].unique())

125

In [166]:
a = data_wrk[data_wrk['FINAL_CALL_TYPE'] == 'VENOM']

In [168]:
a.shape

(43, 13)

In [114]:
#take mode of zipcode from 'INCIDENT_DISPATCH_AREA' to replace all zipcode NaN

mv['ZIPCODE_mv'] = pd.DataFrame(data.groupby('INCIDENT_DISPATCH_AREA')['ZIPCODE'].apply(lambda x: x.value_counts().index[0]))

In [115]:
mv['PRECINCT_mv'] = pd.DataFrame(data.groupby('INCIDENT_DISPATCH_AREA')['POLICEPRECINCT'].apply(lambda x: x.value_counts().index[0]))

In [116]:
mv

                        ZIPCODE_mv  PRECINCT_mv
INCIDENT_DISPATCH_AREA
B1                         10456.0         40.0
B2                         10457.0         44.0
B3                         10472.0         43.0
B4                         10467.0         47.0
B5                         10468.0         52.0
BO                         10452.0         44.0
C1                         10461.0         49.0
CW                         10035.0         25.0
K1                         11235.0         60.0
K2                         11220.0         68.0
K3                         11203.0         67.0
K4                         11207.0         75.0
K5                         11216.0         77.0
K6                         11201.0         84.0
K7                         11206.0         83.0
M1                         10002.0          1.0
M2                         10003.0         13.0
M3                         10019.0         14.0
M4                         10025.0         24.0
M5                         10029.0         19.0
M6                         10027.0         26.0
M7                         10035.0         25.0
M8                         10030.0         32.0
M9                         10032.0         34.0
Q1                         11691.0        101.0
Q2                         11434.0        103.0
Q3                         11419.0        102.0
Q4                         11385.0        104.0
Q5                         11432.0        107.0
Q6                         11368.0        114.0
Q7                         11354.0        109.0
S1                         10301.0        120.0
S2                         10314.0        122.0
S3                         10312.0        123.0
X1                         11213.0         77.0
X2                         10023.0         20.0
X3                         11233.0         81.0
X4                         11359.0        109.0
X5                         10025.0         24.0

In [117]:
mv_clean = data_wrk.merge(mv,on = 'INCIDENT_DISPATCH_AREA')
mv_clean

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA,ZIPCODE_mv,PRECINCT_mv
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
1,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
2,11:38:46 PM,12/31/2018,UNC,2,UNC,2,109.0,N,93.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
3,11:24:58 PM,12/31/2018,SICK,6,SICK,6,414.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
4,11:23:35 PM,12/31/2018,SICMIN,7,SICMIN,7,888.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
5,11:12:16 PM,12/31/2018,EDP,7,EDP,7,662.0,N,82.0,BROOKLYN,11218.0,72.0,K6,11201.0,84.0
6,11:11:42 PM,12/31/2018,UNC,2,UNC,2,608.0,N,82.0,BROOKLYN,11217.0,88.0,K6,11201.0,84.0
7,11:10:33 PM,12/31/2018,PEDSTR,3,PEDSTR,3,422.0,N,93.0,BROOKLYN,11238.0,78.0,K6,11201.0,84.0
8,11:08:20 PM,12/31/2018,EDP,7,EDP,7,1117.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
9,11:06:25 PM,12/31/2018,INBLED,3,INBLED,3,658.0,N,82.0,BROOKLYN,11238.0,79.0,K6,11201.0,84.0
10,11:04:54 PM,12/31/2018,SICK,6,SICK,6,668.0,N,93.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
11,10:52:10 PM,12/31/2018,DRUG,4,DRUG,4,323.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
12,10:46:37 PM,12/31/2018,MVAINJ,4,MVAINJ,4,188.0,N,82.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
13,10:30:43 PM,12/31/2018,EDP,7,EDP,7,269.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
14,10:09:29 PM,12/31/2018,INJMAJ,3,INJMAJ,3,390.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
15,10:08:50 PM,12/31/2018,SEIZR,3,SEIZR,3,443.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
16,10:04:44 PM,12/31/2018,DRUG,4,DRUG,4,NaN,N,87.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
17,09:57:51 PM,12/31/2018,SICK,6,SICK,6,654.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
18,09:56:21 PM,12/31/2018,ABDPN,5,ABDPN,5,307.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
19,09:56:00 PM,12/31/2018,SEIZR,3,SEIZR,3,351.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
20,09:51:13 PM,12/31/2018,UNKNOW,4,UNKNOW,4,144.0,N,87.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
21,09:48:47 PM,12/31/2018,SICK,6,SICK,6,540.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
22,09:46:38 PM,12/31/2018,INJURY,5,INJURY,5,351.0,N,82.0,BROOKLYN,11217.0,84.0,K6,11201.0,84.0
23,09:27:11 PM,12/31/2018,EDP,7,EDP,7,543.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
24,09:10:22 PM,12/31/2018,INJURY,5,UNKNOW,4,373.0,N,93.0,BROOKLYN,11205.0,79.0,K6,11201.0,84.0
25,09:09:39 PM,12/31/2018,DRUG,4,DRUG,4,246.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
26,09:05:35 PM,12/31/2018,INHALE,5,ALTMEN,3,151.0,N,94.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
27,08:56:58 PM,12/31/2018,SICK,6,SICK,6,646.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
28,08:50:55 PM,12/31/2018,DRUG,4,DRUG,4,315.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
29,08:46:28 PM,12/31/2018,UNKNOW,4,UNKNOW,4,485.0,N,93.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001458,12:36:44 AM,01/04/2017,STNDBY,8,STNDBY,8,0.0,N,87.0,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001459,06:38:27 AM,01/03/2017,STNDBY,8,STNDBY,8,861.0,N,91.0,MANHATTAN,10035.0,25.0,CW,10035.0,25.0
3001460,05:16:52 AM,01/03/2017,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,NaN,NaN,CW,10035.0,25.0
3001461,05:15:43 AM,01/03/2017,STNDBY,8,STNDBY,8,0.0,N,91.0,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001462,12:54:58 AM,01/02/2017,STNDBY,8,STNDBY,8,0.0,N,NaN,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001463,01:59:09 PM,11/04/2018,UNC,2,UNC,2,841.0,N,90.0,MANHATTAN,10024.0,20.0,X2,10023.0,20.0
3001464,01:58:27 PM,11/04/2018,SICK,6,SICK,6,NaN,Y,96.0,MANHATTAN,NaN,NaN,X2,10023.0,20.0
3001465,01:52:58 PM,11/04/2018,DIFFBR,2,DIFFBR,2,405.0,N,90.0,MANHATTAN,10022.0,19.0,X2,10023.0,20.0
3001466,10:18:51 AM,11/04/2018,UNKNOW,4,UNKNOW,4,1363.0,N,94.0,MANHATTAN,10025.0,24.0,X2,10023.0,20.0
3001467,06:22:20 PM,11/05/2017,INJURY,5,INJURY,5,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001468,03:16:19 PM,11/05/2017,ALTMEN,3,ALTMEN,3,0.0,N,87.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001469,03:13:04 PM,11/05/2017,INJURY,5,INJURY,5,2836.0,N,90.0,MANHATTAN,10065.0,19.0,X2,10023.0,20.0
3001470,03:10:50 PM,11/05/2017,SICK,6,SICK,6,6133.0,N,90.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001471,02:53:45 PM,11/05/2017,SICK,6,SICK,6,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001472,02:27:19 PM,11/05/2017,UNKNOW,4,UNKNOW,4,284.0,N,90.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001473,02:23:16 PM,11/05/2017,SICK,6,SICK,6,NaN,N,87.0,MANHATTAN,10029.0,23.0,X2,10023.0,20.0
3001474,01:48:39 PM,11/05/2017,ALTMEN,3,ALTMEN,3,975.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001475,01:46:57 PM,11/05/2017,ALTMEN,3,ALTMEN,3,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001476,05:34:09 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X2,10023.0,20.0
3001477,06:59:12 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,BRONX,10463.0,50.0,X3,11233.0,81.0
3001478,06:51:40 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,82.0,BRONX,10461.0,49.0,X3,11233.0,81.0
3001479,05:34:18 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X3,11233.0,81.0
3001480,06:56:26 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,87.0,QUEENS,11377.0,108.0,X4,11359.0,109.0
3001481,06:44:15 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,11359.0,109.0,X4,11359.0,109.0
3001482,06:51:48 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,11365.0,107.0,X5,10025.0,24.0
3001483,06:50:22 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,87.0,BRONX,NaN,NaN,X5,10025.0,24.0
3001484,06:47:32 AM,10/20/2018,STNDBY,8,STNDBY,3,0.0,N,91.0,MANHATTAN,10025.0,24.0,X5,10025.0,24.0
3001485,09:29:29 AM,06/07/2017,OTHER,6,OTHER,6,9.0,N,82.0,BRONX,10461.0,49.0,C1,10461.0,49.0
3001486,07:33:24 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0
3001487,07:30:48 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0

In [118]:
mv_clean.loc[mv_clean['ZIPCODE'].isnull(),['ZIPCODE']] = mv_clean["ZIPCODE_mv"]
mv_clean.loc[mv_clean['POLICEPRECINCT'].isnull(),['POLICEPRECINCT']] = mv_clean["PRECINCT_mv"]

In [101]:
mv_clean

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA,ZIPCODE_mv,PRECINCT_mv
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
1,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
2,11:38:46 PM,12/31/2018,UNC,2,UNC,2,109.0,N,93.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
3,11:24:58 PM,12/31/2018,SICK,6,SICK,6,414.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
4,11:23:35 PM,12/31/2018,SICMIN,7,SICMIN,7,888.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
5,11:12:16 PM,12/31/2018,EDP,7,EDP,7,662.0,N,82.0,BROOKLYN,11218.0,72.0,K6,11201.0,84.0
6,11:11:42 PM,12/31/2018,UNC,2,UNC,2,608.0,N,82.0,BROOKLYN,11217.0,88.0,K6,11201.0,84.0
7,11:10:33 PM,12/31/2018,PEDSTR,3,PEDSTR,3,422.0,N,93.0,BROOKLYN,11238.0,78.0,K6,11201.0,84.0
8,11:08:20 PM,12/31/2018,EDP,7,EDP,7,1117.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
9,11:06:25 PM,12/31/2018,INBLED,3,INBLED,3,658.0,N,82.0,BROOKLYN,11238.0,79.0,K6,11201.0,84.0
10,11:04:54 PM,12/31/2018,SICK,6,SICK,6,668.0,N,93.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
11,10:52:10 PM,12/31/2018,DRUG,4,DRUG,4,323.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
12,10:46:37 PM,12/31/2018,MVAINJ,4,MVAINJ,4,188.0,N,82.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
13,10:30:43 PM,12/31/2018,EDP,7,EDP,7,269.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
14,10:09:29 PM,12/31/2018,INJMAJ,3,INJMAJ,3,390.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
15,10:08:50 PM,12/31/2018,SEIZR,3,SEIZR,3,443.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
16,10:04:44 PM,12/31/2018,DRUG,4,DRUG,4,NaN,N,87.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
17,09:57:51 PM,12/31/2018,SICK,6,SICK,6,654.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
18,09:56:21 PM,12/31/2018,ABDPN,5,ABDPN,5,307.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
19,09:56:00 PM,12/31/2018,SEIZR,3,SEIZR,3,351.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
20,09:51:13 PM,12/31/2018,UNKNOW,4,UNKNOW,4,144.0,N,87.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
21,09:48:47 PM,12/31/2018,SICK,6,SICK,6,540.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
22,09:46:38 PM,12/31/2018,INJURY,5,INJURY,5,351.0,N,82.0,BROOKLYN,11217.0,84.0,K6,11201.0,84.0
23,09:27:11 PM,12/31/2018,EDP,7,EDP,7,543.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
24,09:10:22 PM,12/31/2018,INJURY,5,UNKNOW,4,373.0,N,93.0,BROOKLYN,11205.0,79.0,K6,11201.0,84.0
25,09:09:39 PM,12/31/2018,DRUG,4,DRUG,4,246.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
26,09:05:35 PM,12/31/2018,INHALE,5,ALTMEN,3,151.0,N,94.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
27,08:56:58 PM,12/31/2018,SICK,6,SICK,6,646.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
28,08:50:55 PM,12/31/2018,DRUG,4,DRUG,4,315.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
29,08:46:28 PM,12/31/2018,UNKNOW,4,UNKNOW,4,485.0,N,93.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001458,12:36:44 AM,01/04/2017,STNDBY,8,STNDBY,8,0.0,N,87.0,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001459,06:38:27 AM,01/03/2017,STNDBY,8,STNDBY,8,861.0,N,91.0,MANHATTAN,10035.0,25.0,CW,10035.0,25.0
3001460,05:16:52 AM,01/03/2017,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,10035.0,25.0,CW,10035.0,25.0
3001461,05:15:43 AM,01/03/2017,STNDBY,8,STNDBY,8,0.0,N,91.0,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001462,12:54:58 AM,01/02/2017,STNDBY,8,STNDBY,8,0.0,N,NaN,MANHATTAN,10026.0,28.0,CW,10035.0,25.0
3001463,01:59:09 PM,11/04/2018,UNC,2,UNC,2,841.0,N,90.0,MANHATTAN,10024.0,20.0,X2,10023.0,20.0
3001464,01:58:27 PM,11/04/2018,SICK,6,SICK,6,NaN,Y,96.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001465,01:52:58 PM,11/04/2018,DIFFBR,2,DIFFBR,2,405.0,N,90.0,MANHATTAN,10022.0,19.0,X2,10023.0,20.0
3001466,10:18:51 AM,11/04/2018,UNKNOW,4,UNKNOW,4,1363.0,N,94.0,MANHATTAN,10025.0,24.0,X2,10023.0,20.0
3001467,06:22:20 PM,11/05/2017,INJURY,5,INJURY,5,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001468,03:16:19 PM,11/05/2017,ALTMEN,3,ALTMEN,3,0.0,N,87.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001469,03:13:04 PM,11/05/2017,INJURY,5,INJURY,5,2836.0,N,90.0,MANHATTAN,10065.0,19.0,X2,10023.0,20.0
3001470,03:10:50 PM,11/05/2017,SICK,6,SICK,6,6133.0,N,90.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001471,02:53:45 PM,11/05/2017,SICK,6,SICK,6,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001472,02:27:19 PM,11/05/2017,UNKNOW,4,UNKNOW,4,284.0,N,90.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001473,02:23:16 PM,11/05/2017,SICK,6,SICK,6,NaN,N,87.0,MANHATTAN,10029.0,23.0,X2,10023.0,20.0
3001474,01:48:39 PM,11/05/2017,ALTMEN,3,ALTMEN,3,975.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001475,01:46:57 PM,11/05/2017,ALTMEN,3,ALTMEN,3,0.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001476,05:34:09 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X2,10023.0,20.0
3001477,06:59:12 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,BRONX,10463.0,50.0,X3,11233.0,81.0
3001478,06:51:40 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,82.0,BRONX,10461.0,49.0,X3,11233.0,81.0
3001479,05:34:18 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X3,11233.0,81.0
3001480,06:56:26 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,87.0,QUEENS,11377.0,108.0,X4,11359.0,109.0
3001481,06:44:15 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,11359.0,109.0,X4,11359.0,109.0
3001482,06:51:48 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,91.0,QUEENS,11365.0,107.0,X5,10025.0,24.0
3001483,06:50:22 AM,10/20/2018,STNDBY,8,STNDBY,8,0.0,N,87.0,BRONX,10025.0,24.0,X5,10025.0,24.0
3001484,06:47:32 AM,10/20/2018,STNDBY,8,STNDBY,3,0.0,N,91.0,MANHATTAN,10025.0,24.0,X5,10025.0,24.0
3001485,09:29:29 AM,06/07/2017,OTHER,6,OTHER,6,9.0,N,82.0,BRONX,10461.0,49.0,C1,10461.0,49.0
3001486,07:33:24 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0
3001487,07:30:48 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0

In [133]:
mv_clean = mv_clean[mv_clean['INITIAL_CALL_TYPE'] != 'STNDBY']
mv_clean = mv_clean[mv_clean['ZIPCODE'] != 83]

In [134]:
mv_clean

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA,ZIPCODE_mv,PRECINCT_mv
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
1,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
2,11:38:46 PM,12/31/2018,UNC,2,UNC,2,109.0,N,93.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
3,11:24:58 PM,12/31/2018,SICK,6,SICK,6,414.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
4,11:23:35 PM,12/31/2018,SICMIN,7,SICMIN,7,888.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
5,11:12:16 PM,12/31/2018,EDP,7,EDP,7,662.0,N,82.0,BROOKLYN,11218.0,72.0,K6,11201.0,84.0
6,11:11:42 PM,12/31/2018,UNC,2,UNC,2,608.0,N,82.0,BROOKLYN,11217.0,88.0,K6,11201.0,84.0
7,11:10:33 PM,12/31/2018,PEDSTR,3,PEDSTR,3,422.0,N,93.0,BROOKLYN,11238.0,78.0,K6,11201.0,84.0
8,11:08:20 PM,12/31/2018,EDP,7,EDP,7,1117.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
9,11:06:25 PM,12/31/2018,INBLED,3,INBLED,3,658.0,N,82.0,BROOKLYN,11238.0,79.0,K6,11201.0,84.0
10,11:04:54 PM,12/31/2018,SICK,6,SICK,6,668.0,N,93.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
11,10:52:10 PM,12/31/2018,DRUG,4,DRUG,4,323.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
12,10:46:37 PM,12/31/2018,MVAINJ,4,MVAINJ,4,188.0,N,82.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
13,10:30:43 PM,12/31/2018,EDP,7,EDP,7,269.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
14,10:09:29 PM,12/31/2018,INJMAJ,3,INJMAJ,3,390.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
15,10:08:50 PM,12/31/2018,SEIZR,3,SEIZR,3,443.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
16,10:04:44 PM,12/31/2018,DRUG,4,DRUG,4,NaN,N,87.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
17,09:57:51 PM,12/31/2018,SICK,6,SICK,6,654.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
18,09:56:21 PM,12/31/2018,ABDPN,5,ABDPN,5,307.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
19,09:56:00 PM,12/31/2018,SEIZR,3,SEIZR,3,351.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
20,09:51:13 PM,12/31/2018,UNKNOW,4,UNKNOW,4,144.0,N,87.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
21,09:48:47 PM,12/31/2018,SICK,6,SICK,6,540.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
22,09:46:38 PM,12/31/2018,INJURY,5,INJURY,5,351.0,N,82.0,BROOKLYN,11217.0,84.0,K6,11201.0,84.0
23,09:27:11 PM,12/31/2018,EDP,7,EDP,7,543.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
24,09:10:22 PM,12/31/2018,INJURY,5,UNKNOW,4,373.0,N,93.0,BROOKLYN,11205.0,79.0,K6,11201.0,84.0
25,09:09:39 PM,12/31/2018,DRUG,4,DRUG,4,246.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
26,09:05:35 PM,12/31/2018,INHALE,5,ALTMEN,3,151.0,N,94.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
27,08:56:58 PM,12/31/2018,SICK,6,SICK,6,646.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
28,08:50:55 PM,12/31/2018,DRUG,4,DRUG,4,315.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
29,08:46:28 PM,12/31/2018,UNKNOW,4,UNKNOW,4,485.0,N,93.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001407,11:25:01 AM,03/19/2017,INJURY,5,INJURY,5,12.0,N,82.0,MANHATTAN,10014.0,6.0,CW,10035.0,25.0
3001408,10:08:37 AM,03/19/2017,INJURY,5,INJURY,5,517.0,N,82.0,MANHATTAN,10036.0,10.0,CW,10035.0,25.0
3001409,09:50:38 AM,03/19/2017,INJURY,5,INJURY,5,NaN,N,87.0,MANHATTAN,10000.0,22.0,CW,10035.0,25.0
3001410,09:44:46 AM,03/19/2017,CARD,3,CARD,3,281.0,N,82.0,MANHATTAN,10005.0,1.0,CW,10035.0,25.0
3001411,08:25:05 AM,03/19/2017,INJURY,5,INJURY,5,1523.0,N,90.0,MANHATTAN,10065.0,19.0,CW,10035.0,25.0
3001412,08:18:13 AM,03/19/2017,INJURY,5,INJURY,5,583.0,N,82.0,MANHATTAN,10035.0,25.0,CW,10035.0,25.0
3001413,05:51:36 AM,03/19/2017,SPEVNT,8,SPEVNT,8,1745.0,N,91.0,MANHATTAN,10048.0,1.0,CW,10035.0,25.0
3001416,12:10:29 AM,03/11/2017,SPEVNT,8,SPEVNT,8,1391.0,N,91.0,BROOKLYN,10035.0,25.0,CW,10035.0,25.0
3001421,02:31:59 AM,03/02/2017,MVAINJ,4,MVAINJ,4,NaN,N,82.0,MANHATTAN,10036.0,14.0,CW,10035.0,25.0
3001431,06:09:35 AM,02/09/2017,OTHER,6,OTHER,6,NaN,N,NaN,QUEENS,11432.0,107.0,CW,10035.0,25.0
3001432,11:16:14 AM,02/07/2017,STRANS,8,STRANS,8,NaN,N,91.0,QUEENS,10035.0,25.0,CW,10035.0,25.0
3001452,08:06:56 PM,01/09/2017,INJURY,5,INJURY,5,316.0,N,82.0,MANHATTAN,10022.0,18.0,CW,10035.0,25.0
3001463,01:59:09 PM,11/04/2018,UNC,2,UNC,2,841.0,N,90.0,MANHATTAN,10024.0,20.0,X2,10023.0,20.0
3001464,01:58:27 PM,11/04/2018,SICK,6,SICK,6,NaN,Y,96.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001465,01:52:58 PM,11/04/2018,DIFFBR,2,DIFFBR,2,405.0,N,90.0,MANHATTAN,10022.0,19.0,X2,10023.0,20.0
3001466,10:18:51 AM,11/04/2018,UNKNOW,4,UNKNOW,4,1363.0,N,94.0,MANHATTAN,10025.0,24.0,X2,10023.0,20.0
3001467,06:22:20 PM,11/05/2017,INJURY,5,INJURY,5,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001468,03:16:19 PM,11/05/2017,ALTMEN,3,ALTMEN,3,NaN,N,87.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001469,03:13:04 PM,11/05/2017,INJURY,5,INJURY,5,2836.0,N,90.0,MANHATTAN,10065.0,19.0,X2,10023.0,20.0
3001470,03:10:50 PM,11/05/2017,SICK,6,SICK,6,6133.0,N,90.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001471,02:53:45 PM,11/05/2017,SICK,6,SICK,6,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001472,02:27:19 PM,11/05/2017,UNKNOW,4,UNKNOW,4,284.0,N,90.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001473,02:23:16 PM,11/05/2017,SICK,6,SICK,6,NaN,N,87.0,MANHATTAN,10029.0,23.0,X2,10023.0,20.0
3001474,01:48:39 PM,11/05/2017,ALTMEN,3,ALTMEN,3,975.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001475,01:46:57 PM,11/05/2017,ALTMEN,3,ALTMEN,3,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001476,05:34:09 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X2,10023.0,20.0
3001479,05:34:18 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X3,11233.0,81.0
3001485,09:29:29 AM,06/07/2017,OTHER,6,OTHER,6,9.0,N,82.0,BRONX,10461.0,49.0,C1,10461.0,49.0
3001486,07:33:24 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0
3001487,07:30:48 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0

In [135]:
mv_clean['INCIDENT_TRAVEL_TM_SECONDS_QY'] = mv_clean['INCIDENT_TRAVEL_TM_SECONDS_QY'].replace(0,np.NaN)

In [136]:
mv_clean

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA,ZIPCODE_mv,PRECINCT_mv
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
1,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
2,11:38:46 PM,12/31/2018,UNC,2,UNC,2,109.0,N,93.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
3,11:24:58 PM,12/31/2018,SICK,6,SICK,6,414.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
4,11:23:35 PM,12/31/2018,SICMIN,7,SICMIN,7,888.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
5,11:12:16 PM,12/31/2018,EDP,7,EDP,7,662.0,N,82.0,BROOKLYN,11218.0,72.0,K6,11201.0,84.0
6,11:11:42 PM,12/31/2018,UNC,2,UNC,2,608.0,N,82.0,BROOKLYN,11217.0,88.0,K6,11201.0,84.0
7,11:10:33 PM,12/31/2018,PEDSTR,3,PEDSTR,3,422.0,N,93.0,BROOKLYN,11238.0,78.0,K6,11201.0,84.0
8,11:08:20 PM,12/31/2018,EDP,7,EDP,7,1117.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
9,11:06:25 PM,12/31/2018,INBLED,3,INBLED,3,658.0,N,82.0,BROOKLYN,11238.0,79.0,K6,11201.0,84.0
10,11:04:54 PM,12/31/2018,SICK,6,SICK,6,668.0,N,93.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
11,10:52:10 PM,12/31/2018,DRUG,4,DRUG,4,323.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
12,10:46:37 PM,12/31/2018,MVAINJ,4,MVAINJ,4,188.0,N,82.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
13,10:30:43 PM,12/31/2018,EDP,7,EDP,7,269.0,N,90.0,BROOKLYN,11215.0,78.0,K6,11201.0,84.0
14,10:09:29 PM,12/31/2018,INJMAJ,3,INJMAJ,3,390.0,N,82.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
15,10:08:50 PM,12/31/2018,SEIZR,3,SEIZR,3,443.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
16,10:04:44 PM,12/31/2018,DRUG,4,DRUG,4,NaN,N,87.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
17,09:57:51 PM,12/31/2018,SICK,6,SICK,6,654.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
18,09:56:21 PM,12/31/2018,ABDPN,5,ABDPN,5,307.0,N,82.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
19,09:56:00 PM,12/31/2018,SEIZR,3,SEIZR,3,351.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
20,09:51:13 PM,12/31/2018,UNKNOW,4,UNKNOW,4,144.0,N,87.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
21,09:48:47 PM,12/31/2018,SICK,6,SICK,6,540.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
22,09:46:38 PM,12/31/2018,INJURY,5,INJURY,5,351.0,N,82.0,BROOKLYN,11217.0,84.0,K6,11201.0,84.0
23,09:27:11 PM,12/31/2018,EDP,7,EDP,7,543.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
24,09:10:22 PM,12/31/2018,INJURY,5,UNKNOW,4,373.0,N,93.0,BROOKLYN,11205.0,79.0,K6,11201.0,84.0
25,09:09:39 PM,12/31/2018,DRUG,4,DRUG,4,246.0,N,93.0,BROOKLYN,11205.0,88.0,K6,11201.0,84.0
26,09:05:35 PM,12/31/2018,INHALE,5,ALTMEN,3,151.0,N,94.0,BROOKLYN,11231.0,76.0,K6,11201.0,84.0
27,08:56:58 PM,12/31/2018,SICK,6,SICK,6,646.0,N,82.0,BROOKLYN,11238.0,88.0,K6,11201.0,84.0
28,08:50:55 PM,12/31/2018,DRUG,4,DRUG,4,315.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0
29,08:46:28 PM,12/31/2018,UNKNOW,4,UNKNOW,4,485.0,N,93.0,BROOKLYN,11217.0,78.0,K6,11201.0,84.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3001407,11:25:01 AM,03/19/2017,INJURY,5,INJURY,5,12.0,N,82.0,MANHATTAN,10014.0,6.0,CW,10035.0,25.0
3001408,10:08:37 AM,03/19/2017,INJURY,5,INJURY,5,517.0,N,82.0,MANHATTAN,10036.0,10.0,CW,10035.0,25.0
3001409,09:50:38 AM,03/19/2017,INJURY,5,INJURY,5,NaN,N,87.0,MANHATTAN,10000.0,22.0,CW,10035.0,25.0
3001410,09:44:46 AM,03/19/2017,CARD,3,CARD,3,281.0,N,82.0,MANHATTAN,10005.0,1.0,CW,10035.0,25.0
3001411,08:25:05 AM,03/19/2017,INJURY,5,INJURY,5,1523.0,N,90.0,MANHATTAN,10065.0,19.0,CW,10035.0,25.0
3001412,08:18:13 AM,03/19/2017,INJURY,5,INJURY,5,583.0,N,82.0,MANHATTAN,10035.0,25.0,CW,10035.0,25.0
3001413,05:51:36 AM,03/19/2017,SPEVNT,8,SPEVNT,8,1745.0,N,91.0,MANHATTAN,10048.0,1.0,CW,10035.0,25.0
3001416,12:10:29 AM,03/11/2017,SPEVNT,8,SPEVNT,8,1391.0,N,91.0,BROOKLYN,10035.0,25.0,CW,10035.0,25.0
3001421,02:31:59 AM,03/02/2017,MVAINJ,4,MVAINJ,4,NaN,N,82.0,MANHATTAN,10036.0,14.0,CW,10035.0,25.0
3001431,06:09:35 AM,02/09/2017,OTHER,6,OTHER,6,NaN,N,NaN,QUEENS,11432.0,107.0,CW,10035.0,25.0
3001432,11:16:14 AM,02/07/2017,STRANS,8,STRANS,8,NaN,N,91.0,QUEENS,10035.0,25.0,CW,10035.0,25.0
3001452,08:06:56 PM,01/09/2017,INJURY,5,INJURY,5,316.0,N,82.0,MANHATTAN,10022.0,18.0,CW,10035.0,25.0
3001463,01:59:09 PM,11/04/2018,UNC,2,UNC,2,841.0,N,90.0,MANHATTAN,10024.0,20.0,X2,10023.0,20.0
3001464,01:58:27 PM,11/04/2018,SICK,6,SICK,6,NaN,Y,96.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001465,01:52:58 PM,11/04/2018,DIFFBR,2,DIFFBR,2,405.0,N,90.0,MANHATTAN,10022.0,19.0,X2,10023.0,20.0
3001466,10:18:51 AM,11/04/2018,UNKNOW,4,UNKNOW,4,1363.0,N,94.0,MANHATTAN,10025.0,24.0,X2,10023.0,20.0
3001467,06:22:20 PM,11/05/2017,INJURY,5,INJURY,5,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001468,03:16:19 PM,11/05/2017,ALTMEN,3,ALTMEN,3,NaN,N,87.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001469,03:13:04 PM,11/05/2017,INJURY,5,INJURY,5,2836.0,N,90.0,MANHATTAN,10065.0,19.0,X2,10023.0,20.0
3001470,03:10:50 PM,11/05/2017,SICK,6,SICK,6,6133.0,N,90.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001471,02:53:45 PM,11/05/2017,SICK,6,SICK,6,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001472,02:27:19 PM,11/05/2017,UNKNOW,4,UNKNOW,4,284.0,N,90.0,MANHATTAN,10000.0,22.0,X2,10023.0,20.0
3001473,02:23:16 PM,11/05/2017,SICK,6,SICK,6,NaN,N,87.0,MANHATTAN,10029.0,23.0,X2,10023.0,20.0
3001474,01:48:39 PM,11/05/2017,ALTMEN,3,ALTMEN,3,975.0,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001475,01:46:57 PM,11/05/2017,ALTMEN,3,ALTMEN,3,NaN,N,82.0,MANHATTAN,10023.0,20.0,X2,10023.0,20.0
3001476,05:34:09 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X2,10023.0,20.0
3001479,05:34:18 AM,02/09/2017,EDP,7,EDP,7,NaN,N,NaN,BROOKLYN,11233.0,81.0,X3,11233.0,81.0
3001485,09:29:29 AM,06/07/2017,OTHER,6,OTHER,6,9.0,N,82.0,BRONX,10461.0,49.0,C1,10461.0,49.0
3001486,07:33:24 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0
3001487,07:30:48 AM,04/26/2017,OTHER,6,OTHER,6,NaN,N,NaN,BRONX,10452.0,44.0,BO,10452.0,44.0

In [149]:
travel = mv_clean[['ZIPCODE',"INITIAL_SEVERITY_LEVEL_CODE", 'INCIDENT_TRAVEL_TM_SECONDS_QY']].groupby(['ZIPCODE',"INITIAL_SEVERITY_LEVEL_CODE"]).mean()

KeyError: "['INCIDENT_TRAVEL_TM_SECONDS_QY'] not in index"

In [150]:
travel

                                     INCIDENT_TRAVEL_TM_SECONDS_QY
ZIPCODE INITIAL_SEVERITY_LEVEL_CODE
10000.0 1                                               123.000000
        2                                               536.041667
        3                                               528.869565
        4                                               641.282051
        5                                               722.900826
        6                                               700.107143
        7                                               887.568182
        8                                              1232.000000
10001.0 1                                               249.702550
        2                                               376.279070
        3                                               376.389774
        4                                               500.230435
        5                                               525.106300
        6                                               536.703435
        7                                               894.119449
        8                                                      NaN
10002.0 1                                               234.903166
        2                                               361.073019
        3                                               355.165326
        4                                               450.461101
        5                                               455.196698
        6                                               491.308496
        7                                               691.351080
        8                                              1581.666667
10003.0 1                                               220.864553
        2                                               321.321032
        3                                               318.667029
        4                                               410.426494
        5                                               421.103249
        6                                               444.233696
...                                                            ...
11692.0 7                                               418.294347
11693.0 1                                               260.215686
        2                                               335.917219
        3                                               322.118110
        4                                               339.181013
        5                                               350.942484
        6                                               373.307042
        7                                               392.502712
11694.0 1                                               250.851190
        2                                               322.147736
        3                                               327.436198
        4                                               370.608350
        5                                               374.038627
        6                                               408.051282
        7                                               463.218415
        8                                               235.000000
11695.0 2                                               542.777778
        3                                               572.555556
        4                                               586.000000
        5                                               541.857143
        6                                               736.500000
        7                                               620.666667
11697.0 1                                               706.666667
        2                                               723.253968
        3                                               768.438095
        4                                               759.265896
        5                                               866.869565
        6                                               933.280702
        7                                              1025.901961
12345.0 7                                               740.000000

[1722 rows x 1 columns]

In [145]:
travel.loc[11697]

                             INCIDENT_TRAVEL_TM_SECONDS_QY
INITIAL_SEVERITY_LEVEL_CODE
1                                               706.666667
2                                               723.253968
3                                               768.438095
4                                               759.265896
5                                               866.869565
6                                               933.280702
7                                              1025.901961

In [151]:
travel.loc[10314]

                             INCIDENT_TRAVEL_TM_SECONDS_QY
INITIAL_SEVERITY_LEVEL_CODE
1                                               286.112469
2                                               384.921527
3                                               369.446379
4                                               415.161057
5                                               429.857764
6                                               435.831751
7                                               610.148131
9                                                 7.000000

In [154]:
travel.loc[11201]

                             INCIDENT_TRAVEL_TM_SECONDS_QY
INITIAL_SEVERITY_LEVEL_CODE
1                                               232.832432
2                                               349.858689
3                                               349.078326
4                                               451.460599
5                                               461.340072
6                                               455.003718
7                                               662.146272
8                                              4360.400000

In [ ]:
## zipcodes with 83 are bad data

In [152]:
#replace all NaN 

mv_clean = mv_clean.merge(travel,on = ['ZIPCODE','INITIAL_SEVERITY_LEVEL_CODE'])

In [153]:
mv_clean #delete special event SPEVNT

,Incident_Date,Incident_Time,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,INCIDENT_TRAVEL_TM_SECONDS_QY_x,HELD_INDICATOR,INCIDENT_DISPOSITION_CODE,BOROUGH,ZIPCODE,POLICEPRECINCT,INCIDENT_DISPATCH_AREA,ZIPCODE_mv,PRECINCT_mv,INCIDENT_TRAVEL_TM_SECONDS_QY_y,INCIDENT_TRAVEL_TM_SECONDS_QY
0,11:59:46 PM,12/31/2018,CARDBR,2,CARDBR,2,453.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
1,11:49:42 PM,12/31/2018,UNC,2,UNC,2,303.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
2,08:11:30 PM,12/31/2018,ANAPH,2,ANAPH,2,380.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
3,06:59:33 PM,12/31/2018,DIFFBR,2,DIFFBR,2,NaN,N,93.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
4,04:40:10 PM,12/31/2018,STATEP,2,STATEP,2,167.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
5,01:34:04 PM,12/31/2018,STATEP,2,STATEP,2,31.0,N,90.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
6,09:47:08 AM,12/31/2018,DIFFBR,2,DIFFBR,2,247.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
7,09:06:17 AM,12/31/2018,ASTHMB,2,ASTHMB,2,394.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
8,02:58:59 AM,12/31/2018,CARDBR,2,CARDBR,2,317.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
9,02:57:50 AM,12/31/2018,UNC,2,UNC,2,189.0,N,91.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
10,11:33:50 PM,12/30/2018,UNC,2,UNC,2,287.0,N,90.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
11,11:06:34 PM,12/30/2018,DIFFBR,2,DIFFBR,2,168.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
12,06:12:44 PM,12/30/2018,CARDBR,2,CARDBR,2,423.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
13,04:36:01 PM,12/30/2018,CVAC,2,CVAC,2,303.0,N,82.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
14,02:30:18 PM,12/30/2018,DIFFBR,2,DIFFBR,2,258.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
15,12:35:47 PM,12/30/2018,UNC,2,ARREST,1,432.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
16,10:22:29 AM,12/30/2018,ASTHMB,2,ASTHMB,2,126.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
17,07:10:34 AM,12/30/2018,UNC,2,UNC,2,148.0,N,90.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
18,03:52:08 AM,12/30/2018,UNC,2,UNC,2,484.0,N,90.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
19,06:51:23 PM,12/29/2018,DIFFBR,2,DIFFBR,2,547.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
20,06:16:02 PM,12/29/2018,ANAPH,2,ANAPH,2,442.0,N,82.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
21,03:20:37 PM,12/29/2018,UNC,2,UNC,2,179.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
22,03:17:36 PM,12/29/2018,UNC,2,UNC,2,343.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
23,02:54:52 PM,12/29/2018,DIFFBR,2,DIFFBR,2,251.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
24,09:44:19 AM,12/29/2018,DIFFBR,2,DIFFBR,2,307.0,N,82.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
25,08:15:53 AM,12/29/2018,UNC,2,UNC,2,459.0,N,96.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
26,06:14:59 AM,12/29/2018,CARDBR,2,CARDBR,2,198.0,N,82.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
27,04:09:12 AM,12/29/2018,DIFFBR,2,DIFFBR,2,369.0,N,82.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
28,02:00:40 AM,12/29/2018,DIFFBR,2,DIFFBR,2,336.0,N,90.0,BROOKLYN,11201.0,84.0,K6,11201.0,84.0,349.858689,349.858689
29,11:32:20 PM,12/28/2018,DIFFBR,2,DIFFBR,2,203.0,N,82.0,BROOKLYN,11201.0,88.0,K6,11201.0,84.0,349.858689,349.858689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2992889,07:07:59 PM,02/10/2017,ARREST,1,ARREST,1,498.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992890,02:01:59 PM,02/07/2017,ARREST,1,ARREST,1,179.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992891,05:05:48 PM,02/03/2017,ARREST,1,ARREST,1,161.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992892,05:37:36 AM,02/02/2017,ARREST,1,ARREST,1,343.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992893,04:26:20 AM,01/27/2017,ARREST,1,ARREST,1,281.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992894,08:32:23 AM,01/23/2017,ARREST,1,ARREST,1,326.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992895,01:58:33 AM,01/23/2017,ARREST,1,ARREST,1,252.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992896,06:10:31 PM,01/22/2017,ARREST,1,ARREST,1,279.0,N,93.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992897,02:26:16 PM,01/21/2017,ARREST,1,ARREST,1,193.0,N,93.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992898,09:10:31 AM,01/19/2017,ARREST,1,ARREST,1,253.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992899,12:12:26 PM,01/18/2017,ARREST,1,ARREST,1,248.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992900,06:00:21 PM,01/17/2017,CHOKE,1,CHOKE,1,398.0,N,93.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992901,12:42:49 PM,01/17/2017,ARREST,1,ARREST,1,241.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992902,04:57:00 AM,01/17/2017,ARREST,1,ARREST,1,377.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992903,02:10:39 PM,01/16/2017,ARREST,1,ARREST,1,336.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992904,09:46:55 AM,01/16/2017,ARREST,1,ARREST,1,203.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992905,07:04:30 PM,01/15/2017,ARREST,1,ARREST,1,237.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992906,07:01:08 AM,01/14/2017,ARREST,1,ARREST,1,348.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992907,11:09:13 PM,01/07/2017,ARREST,1,ARREST,1,623.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992908,10:18:00 AM,01/07/2017,ARREST,1,ARREST,1,127.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992909,04:51:47 PM,01/06/2017,ARREST,1,ARREST,1,329.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992910,10:28:31 PM,01/03/2017,ARREST,1,ARREST,1,272.0,N,83.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992911,06:26:17 PM,01/03/2017,ARREST,1,ARREST,1,307.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992912,04:49:17 AM,01/03/2017,ARREST,1,ARREST,1,243.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992913,09:34:19 PM,01/01/2017,ARREST,1,ARREST,1,145.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,283.608997,283.608997
2992914,10:59:14 PM,05/25/2018,MOSINJ,9,INJURY,5,7.0,N,82.0,RICHMOND / STATEN ISLAND,10314.0,122.0,S2,10314.0,122.0,7.000000,7.000000
2992915,05:45:23 AM,01/30/2017,MCI21,8,MCI22P,2,251.0,N,82.0,RICHMOND / STATEN ISLAND,10306.0,122.0,S2,10314.0,122.0,251.000000,251.000000
2992916,10:58:12 PM,12/28/2018,SPEVNT,8,SPEVNT,8,NaN,N,NaN,MANHATTAN,10036.0,14.0,X1,11213.0,77.0,NaN,NaN
2992917,12:50:42 AM,12/31/2017,SPEVNT,8,SPEVNT,8,NaN,N,87.0,MANHATTAN,10036.0,14.0,CW,10035.0,25.0,NaN,NaN
2992918,01:21:35 AM,09/19/2017,SPEVNT,8,SPEVNT,8,NaN,N,87.0,MANHATTAN,10026.0,28.0,CW,10035.0,25.0,NaN,NaN

In [112]:
travel['ZIPCODE']

SyntaxError: invalid syntax (<ipython-input-112-b4fcdc04e914>, line 1)

In [110]:
travel.loc[travel['ZIPCODE'] == 11201]

KeyError: 'ZIPCODE'